# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               GradientOverflow
tagline:             'Learning Blog'
description:         'If you would thoroughly know everything, teach it to others.'
url:                 https://gradientoverflow.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Joohan Na
  url:               https://github.com/gradientoverflow
  email:             gradient.overflow@gmail.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

google_analytics:
  ua: 'UA-109898110-1'

github:
  repo: 'https://github.com/gradientoverflow'

category_dir: category/
tag_dir: tag/

excerpt_separator: ""
